spring:
  application:
    name: user-accounts
    base-prefix: /api/1
    job:
      user-balance:
        cron: "*/1 * * * * ?"
    jwt:
      secret: =================================ACCOUNTS===============================
      expirationMs: 1000000000

  datasource:
    url: jdbc:postgresql://localhost:5432/user_accounts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  elasticsearch:
    uris: http://localhost:9200
    connection-timeout: 1s

  data:
    redis:
      host: localhost
      port: 6379